name: caddy
services:
  caddy-cloudflaredns:
    image: slothcroissant/caddy-cloudflaredns:latest
    container_name: caddy
    env_file: .env
    stdin_open: true
    tty: true
    networks:
      macvlan_network:
        ipv4_address: 10.1.1.26
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - ACME_AGREE=true
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
    name: caddy_data
  caddy_config:
    external: true
    name: caddy_config

networks:
  macvlan_network:
    external: true