---
- name: deploy pihole
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - sudo

    - name: Download Pi-hole installation script
      get_url:
        url: https://install.pi-hole.net
        dest: /tmp/install_pihole.sh
        mode: '0755'

    - name: Run Pi-hole installation script
      command: "bash /tmp/install_pihole.sh --unattended"

    - name: Ensure Pi-hole is running
      service:
        name: pihole-FTL
        state: started
        enabled: yes

    - name: Set Pi-hole admin password
      command: "pihole -a -p {{ lookup('env', 'PIHOLE_PASSWORD') }}"
      args:
        creates: /etc/pihole/setupVars.conf