---
- hosts: pve2
  become: true
  tasks:
    - name: standard packages
      apt:
        pkg: 
        - vim
        - git
        - gpg
        - htop
        - curl
        - unzip
        - rsync
        - rclone
        - dnsutils
        - nfs-common
        - python3-pip
        - build-essential
        - python3-setuptools
        - prometheus-node-exporter
        update_cache: yes
  
    - name: bashrc
      get_url: 
        url: https://raw.githubusercontent.com/rtyner/homelab/refs/heads/main/dotfiles/.bashrc
        dest: /root/