---

- hosts: servers
  become: true
  roles:
  - role: artis3n.tailscale
    vars:
      tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
  tasks:

  - name: nopasswd sudo
    lineinfile:
        path: /etc/sudoers
        state: present
        backup: yes
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        
  - name: disable root login
    lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        backup: yes        
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"

  - name: restart ssh
    service:
      name: ssh
      state: restarted
  
  - name: standard packages
    apt:
      pkg: 
      - vim
      - git
      - gpg
      - htop
      - curl
      - unzip
      - rsync
      - rclone
      - dnsutils
      - nfs-common
      - python3-pip
      - build-essential
      - python3-setuptools
      update_cache: yes

  - name: bashrc
    get_url: 
      url: https://raw.githubusercontent.com/rtyner/homelab/refs/heads/main/dotfiles/.bashrc
      dest: /home/rt/
  
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Create a new regular user with sudo privileges
    user:
      name: rt
      state: present
      groups: sudo, docker
      append: true
      create_home: true