---

- hosts: k3s
  become: true
  tasks:

  - name: nopasswd sudo
    lineinfile:
        path: /etc/sudoers
        state: present
        backup: yes
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        
  - name: disable root login
    lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        backup: yes        
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"

  - name: restart ssh
    service:
      name: ssh
      state: restarted
  
  - name: standard packages
    apt:
      pkg: 
      - vim
      - git
      - gpg
      - htop
      - curl
      - unzip
      - rsync
      - rclone
      - dnsutils
      - nfs-common
      - python3-pip
      - build-essential
      - python3-setuptools
      - prometheus-node-exporter
      update_cache: yes

  - name: bashrc
    get_url: 
      url: https://raw.githubusercontent.com/rtyner/homelab/refs/heads/main/dotfiles/.bashrc
      dest: /home/rt/

  - name: Create a new regular user with sudo privileges
    user:
      name: rt
      state: present
      groups: sudo
      append: true
      create_home: true