--- 

- name: drive mount playbook
  hosts: servers
  become: true
  
  vars:
    - red_uri: "//10.1.1.6/red-share"
    - red_mountpoint: "/home/rt/mnt/red"
    - bdp_uri: "//10.1.1.6/big-dick-pool"
    - bdp_mountpoint: "/home/rt/mnt/bdp"
    - arch_uri: "10.1.1.14:/arch-storage"
    - mount_username: "rt"
    - mount_password: "{{ lookup('env', 'MOUNT_PW') }}"
  
  tasks:
  
    - name: update apt 
      apt:
        update_cache: yes
        name: '*'
        force_apt_get: yes
        state: latest
  
    - name: update packages
      apt:
        update_cache: yes
        name: '*'
        force_apt_get: yes
        state: latest
      when: ansible_facts['os_family'] == 'Debian'
  
    - name: install packages
      package:
        name: "{{packages}}"
        state: present
      vars:
        packages:
          - nfs-common
          - cifs-utils
 
    - name: create working dir
      ansible.builtin.file:
        path: /home/rt/working
        state: directory
        owner: rt 
        group: rt
        mode: '0755'

    - name: create mnt
      ansible.builtin.file:
        path: /home/rt/mnt
        state: directory
        owner: rt 
        group: rt
        mode: '0755'
 
    - name: create mnt/red
      ansible.builtin.file:
       path: /home/rt/mnt/red
       state: directory
       owner: rt 
       group: rt
       mode: '0755'

    - name: create mnt/bdp
      ansible.builtin.file:
        path: /home/rt/mnt/bdp
        state: directory
        owner: rt 
        group: rt
        mode: '0755'

    - name: cifs utils
      ansible.builtin.package:
        name: cifs-utils
        state: present
    
    - name: check red mount exists
      ansible.builtin.file:
        path: "{{ red_uri }}"
        state: directory
        mode: '0755'
        owner: rt
        group: rt
 
    - name: mount red
      ansible.posix.mount:
        src: "{{ red_uri }}"
        path: "{{ red_mountpoint }}"
        fstype: cifs
        opts: 'username={{ mount_username }},password={{ mount_password }},user,nofail'
        state: mounted

    - name: mount bdp
      ansible.posix.mount:
        src: "{{ bdp_uri }}"
        path: "{{ bdp_mountpoint }}"
        fstype: cifs
        opts: 'username={{ mount_username }},password={{ mount_password }},user,nofail'
        state: mounted