---
- name: Install qemu-guest-agent
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install QEMU guest agent
      package:
        name: qemu-guest-agent
        state: present
    
    - name: Enable and start QEMU guest agent service
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started