acl internal {
    10.1.1.0/24;
    10.10.1.0/24;
    10.20.1.0/24;
    10.30.1.0/24;
    10.40.1.0/24;
    10.50.1.0/24;
    10.60.1.0/24;
    10.70.1.0/24;
    10.80.1.0/24;
    10.90.1.0/24;
    10.99.1.0/24;
};
options {
    forwarders {
        1.1.1.1;
        8.8.8.8;
    };
    allow-query { internal; };
    listen-on-v6 { none; };
    dnssec-validation no;
};
zone "local.rtyner.com" {
    type master;
    file "/etc/bind/zones/db.local.rtyner.com";
    allow-transfer { 10.1.1.97; }; // IP of the secondary server
    also-notify { 10.1.1.97; }; // IP of the secondary server
};