version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9098:9000"
      - "9099:9001"
    volumes:
      - /mnt/pool-1-14t/rt:/data
    environment:
      MINIO_ROOT_USER: rt
      MINIO_ROOT_PASSWORD: 
    command: server /data --console-address ":9001"
    restart: unless-stopped