version: '3'

services:
  nocodb:
    container_name: nocodb-postgres
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nocodb:/usr/app/data/
    environment:
      NC_DB: "pg://host.docker.internal:5432?u=root&p=password&d=d1"
      NC_AUTH_JWT_SECRET: "569a1821-0a93-45e8-87ab-eb857f20a010"
    networks:
      - docker_npm-net

networks:
  docker_npm-net:
    external: true