- name: Install Longhorn prerequisites
  hosts: k3s
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: 
          - open-iscsi
          - curl
          - util-linux
        state: present
        update_cache: yes

    - name: Enable and start iscsid service
      systemd:
        name: iscsid
        state: started
        enabled: yes