---
- name: Deploy Plex with Docker
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Create Plex directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "rt"
        group: "rt"
        mode: '0755'
      loop:
        - /home/rt/docker/plex/library
        - /home/rt/mnt/bdp/media/tv
        - /home/rt/mnt/bdp/media/movies

    - name: Deploy Plex container
      community.docker.docker_container:
        name: plex
        image: lscr.io/linuxserver/plex:latest
        network_mode: host
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/New_York
          VERSION: docker
          PLEX_CLAIM: "{{ lookup('env', 'PLEX_CLAIM') }}"
        volumes:
          - /home/rt/docker/plex/library:/config
          - /home/rt/mnt/bdp/media/tv:/tv
          - /home/rt/mnt/bdp/media/movies:/movies
        restart_policy: unless-stopped